name: Build and Deploy function

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup GCP
          uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            version: '290.0.1'
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            export_default_credentials: true
        - name: Build
          working-directory: src/
          run: gcloud functions deploy credit-to-debit --entry-point Function --runtime go113
            --set-env-vars
            STARLING_API_KEY=${{ secrets.STARLING_API_KEY }},TRUELAYER_ID=${{ secrets.TRUELAYER_ID }},TRUELAYER_SECRET=${{ secrets.TRUELAYER_SECRET }},TRUELAYER_TOKEN=${{ secrets.TRUELAYER_TOKEN }}
            --trigger-http

